CREATE DATABASE STUDENTS
ON PRIMARY
(NAME = STUDENTS1,
FILENAME = 'E:\DATA\STUDENTS1.mdf',
SIZE = 5,
MAXSIZE = unlimited,
FILEGROWTH = 10%),
FILEGROUP FILEG1
(NAME = STUDENTS12,
FILENAME = 'E:\DATA\STUDENTS2.ndf',
SIZE = 10,
MAXSIZE = 100,
FILEGROWTH = 1)
LOG ON
(NAME = STUDENTSLOG1,
FILENAME = 'E:\DATA\STUDENTSLOG1.ldf',
SIZE = 5,
MAXSIZE = 50,
FILEGROWTH = 1),
(NAME = STUDENTSLOG2,
FILENAME = 'E:\DATA\STUDENTSLOG2.ldf',
SIZE = 5,
MAXSIZE = 50,
filegrowth = 1)