CREATE DATABASE STUDENT2
ON PRIMARY
(NAME = 'STUDENT2_DATA',
FILENAME = 'E:\DATA\STUDENT2_DATA.MDF',
SIZE = 5MB,
MAXSIZE = 20MB,
FILEGROWTH = 20%)
LOG ON
(NAME = 'STUDENT2_LOG',
FILENAME = 'E:\DATA\STUDENT2_LOG.LDF',
SIZE = 5MB,
MAXSIZE = 10MB,
FILEGROWTH = 2MB)